version: '3.8'

services:
  streamlit:
    build: 
      context: .
    restart: always
    container_name: streamlit_app
    expose:
      - "8501"
    ports:
      - 8501:8501
    command: streamlit run app.py